# Generated by Django 4.2.4 on 2023-08-31 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_employee_survey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="survey",
        ),
    ]
