# Generated by Django 4.2.4 on 2023-08-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_answer_created_at_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(),
        ),
    ]
