# Generated by Django 4.2.4 on 2023-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0005_remove_question_survey_survey_survey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="response",
        ),
        migrations.AddField(
            model_name="answer",
            name="rating",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
