# Generated by Django 4.2.4 on 2023-08-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_employee_survey'),
        ('survey', '0007_rename_survey_survey_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='submitted',
        ),
        migrations.CreateModel(
            name='EmployeeServey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted', models.BooleanField(default=False)),
                ('answer', models.ManyToManyField(blank=True, null=True, related_name='asnwers', to='survey.answer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='survey.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_survey', to='accounts.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
